version = 1
SPDX-PackageName = "ui5-manifest"
SPDX-PackageSupplier = "Aleksandr Suvorov <aleksandr.suvorov@sap.com>"
SPDX-PackageDownloadLocation = "https://github.com/SAP/ui5-manifest"

[[annotations]]
path = "**.**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2009-2025 SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"
